# Headset
- type: loadout
  id: HeadofSecurityHeadsetBasic
  equipment:
    ears: ClothingHeadsetHOS

- type: loadout
  id: HeadofSecurityHeadset
  equipment:
    ears: ClothingHeadsetAltSecurity

- type: loadout
  id: HeadofSecurityVeteranHeadset
  equipment:
    ears: ClothingHeadsetHOSveteran

# Head
- type: loadout
  id: HeadofSecurityPatrolCap
  equipment:
    head: ClothingHeadHatHOSsoft

- type: loadout
  id: HeadofSecurityColonelCap
  equipment:
    head: ClothingHeadHatHOSColonelCap

# Outer clothing
- type: loadout
  id: HeadofSecurityGreatcoat
  equipment:
    neck: ClothingNeckCloakHosgreatcoat

- type: loadout
  id: HeadofSecurityWinterCoatUnarmored
  equipment:
    outerClothing: ClothingOuterWinterHoSUnarmored

- type: loadout
  id: HeadofSecurityEliteArmor
  equipment:
    outerClothing: ClothingOuterArmorHoSEliteArmor

- type: loadout
  id: HeadofSecurityBomberJacket
  equipment:
    outerClothing: ClothingOuterCoatHosBomber

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuitGrey
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityJumpskirtGrey
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSGrey
  groupBy: "jumpskirt"

- type: loadout
  id: HeadofSecurityProfessionalJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSPro
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityProfessionalJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSPro
  groupBy: "jumpskirt"

- type: loadout
  id: HeadofSecurityColonelJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSColonel
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityColonelJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSColonel
  groupBy: "jumpskirt"

# Belt
- type: loadout
  id: HeadofSecurityShoulderHolster
  equipment:
    belt: ClothingBeltHolsterHOSFilled

# Firearms
- type: loadout
  id: SecurityPistolSturm
  equipment:
    pocket1: WeaponPistolSturm

- type: loadout
  id: SecurityOfficerKnife
  equipment:
    pocket1: OfficerKnife

# Ammunition
- type: loadout
  id: SecurityAmmoSturm
  storage:
    back:
    - SpeedLoaderSturm
