- type: cargoProduct
  id: SecurityShotgunNonLethal
  icon:
    sprite: _Impstation/Objects/Weapons/Guns/Shotguns/beanbagpumptwo.rsi
    state: icon
  product: CrateSecurityShotgunNonlethal
  cost: 2000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityEvaKit
  icon:
    sprite: _Impstation/Clothing/Head/Helmets/eva_security.rsi
    state: icon
  product: CrateEvaSecurityKit
  cost: 5000
  category: cargoproduct-category-name-security
  group: market